// Ordered skill display list for Step 7.
// Strings = simple named skills. Objects = free-name group slots.
// Occ skills not in this list are appended at the end.

const ALL_SKILLS = [
  'Accounting',
  'Anthropology',
  'Appraise',
  'Archaeology',
  { group: 'Art/Craft',        slots: 3 },
  'Charm',
  'Climb',
  'Cthulhu Mythos',
  'Disguise',
  'Dodge',
  'Drive Auto',
  'Electrical Repair',
  'Fast Talk',
  { group: 'Fighting',         slots: 3 },
  { group: 'Firearms',         slots: 3 },
  'First Aid',
  'History',
  'Intimidate',
  'Jump',
  'Law',
  { group: 'Language (Other)', slots: 3 },
  { group: 'Language (Own)',   slots: 1, defaultName: 'English' },
  'Library Use',
  'Listen',
  'Locksmith',
  'Mechanical Repair',
  'Medicine',
  'Natural World',
  'Navigate',
  'Occult',
  'Operate Hvy Machinery',
  'Persuade',
  { group: 'Pilot',            slots: 2 },
  'Psychology',
  'Psychoanalysis',
  'Ride',
  { group: 'Science',          slots: 3 },
  'Sleight of Hand',
  'Spot Hidden',
  'Stealth',
  { group: 'Survival',         slots: 2 },
  'Swim',
  'Throw',
  'Track',
  { group: 'Misc',             slots: 5 },
];

export default ALL_SKILLS;
