// CoC 7e Occupation Data — 25 occupations from the Keeper Rulebook
// cashAndAssets uses Credit Rating midpoint for display

const mid = (min, max) => Math.floor((min + max) / 2);

const cash = (cr) => ({
  cash:         cr * 2,
  assets:       cr * 50,
  spendingLimit: Math.max(1, Math.floor(cr / 5) * 5),
});

const OCCUPATIONS = [
  {
    id: 'antiquarian',
    name: 'Antiquarian',
    description: 'Collector and expert of antiques, rare books, and curiosities from bygone eras. Often found haunting musty shops and private collections.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 70 },
    compulsorySkills: ['Appraise', 'Art/Craft', 'History', 'Library Use', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'artist',
    name: 'Artist',
    description: 'Painter, sculptor, or craftsperson driven by creative vision. Life is rarely stable, but the work feeds the soul.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft', 'History', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'author',
    name: 'Author',
    description: 'Weaves words into worlds. Novelists, playwrights, and poets who seek truth — and sometimes find it.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['History', 'Library Use', 'Occult', 'Own Language', 'Psychology'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'bounty_hunter',
    name: 'Bounty Hunter',
    description: 'Tracks down fugitives and criminals for reward money. Life on the road, always armed, always watchful.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Drive Auto', 'Electrical Repair', 'Law', 'Psychology', 'Track', 'Stealth'],
    specialtyChoices: [
      { pick: 1, from: ['Fighting (Brawl)', 'Firearms (Handgun)', 'Firearms (Rifle/Shotgun)'], label: 'Combat skill' },
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'clergy',
    name: 'Clergy / Missionary',
    description: 'Minister, priest, or travelling missionary. Brings faith to the faithful — and sometimes confronts what faith cannot explain.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 60 },
    compulsorySkills: ['Accounting', 'History', 'Library Use', 'Listen', 'Natural World', 'Occult', 'Persuade', 'Psychology'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal',
    name: 'Criminal',
    description: 'Operates outside the law — thief, forger, con artist, or hired muscle. Everyone has a specialty in this line of work.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 5, max: 65 },
    compulsorySkills: ['Appraise', 'Disguise', 'Fighting (Brawl)', 'Firearms', 'Listen', 'Locksmith', 'Stealth', 'Spot Hidden'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'detective',
    name: 'Detective',
    description: 'Private investigator or consulting detective. Follows clues where the police won\'t — or can\'t.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 20, max: 45 },
    compulsorySkills: ['Disguise', 'Firearms', 'Law', 'Library Use', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'doctor',
    name: 'Doctor of Medicine',
    description: 'Physician and healer. Trained to understand the human body — though some things defy all medical explanation.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 80 },
    compulsorySkills: ['First Aid', 'Medicine', 'Other Language (Latin)', 'Persuade', 'Psychology', 'Science (Biology)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'drifter',
    name: 'Drifter',
    description: 'No fixed address. No fixed plan. Rides the rails, works odd jobs, and sees more of the world than most.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 0, max: 5 },
    compulsorySkills: ['Climb', 'Jump', 'Listen', 'Navigate', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
      { pick: 1, from: ['Fighting (Brawl)', 'Firearms (Handgun)', 'Fighting (Knife)'], label: 'Combat skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'engineer',
    name: 'Engineer',
    description: 'Builder of bridges, machines, and systems. Applies science to the physical world — and hopes the physical world cooperates.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Electrical Repair', 'Library Use', 'Mechanical Repair', 'Operate Hvy Machinery', 'Science (Physics)'],
    specialtyChoices: [
      { pick: 1, from: ['Science (Engineering)', 'Science (Chemistry)', 'Science (Mathematics)'], label: 'Science specialty' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'entertainer',
    name: 'Entertainer',
    description: 'Performer, showman, or actor. Lives in the spotlight — and sometimes in the shadows behind it.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 9, max: 70 },
    compulsorySkills: ['Art/Craft (Acting)', 'Disguise', 'Listen', 'Psychology'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'farmer',
    name: 'Farmer',
    description: 'Works the land, knows the seasons, and endures. Rural life brings its own quiet horrors — and practical resilience.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Farming)', 'Drive Auto', 'First Aid', 'Mechanical Repair', 'Natural World', 'Track'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'gangster',
    name: 'Gangster',
    description: 'Enforcer or aspiring boss in organised crime. Violence is a tool of the trade.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 5, max: 80 },
    compulsorySkills: ['Drive Auto', 'Fighting (Brawl)', 'Firearms', 'Intimidate', 'Law', 'Listen', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'journalist',
    name: 'Journalist',
    description: 'Chases stories others won\'t touch. The press can go places police can\'t — and sometimes finds things they shouldn\'t.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Photography)', 'History', 'Library Use', 'Own Language', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    description: 'Advocates for clients in court and behind closed doors. Knows where the law bends — and where it breaks.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 80 },
    compulsorySkills: ['Accounting', 'Law', 'Library Use', 'Psychology'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill (1)' },
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill (2)' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'librarian',
    name: 'Librarian',
    description: 'Guardian of knowledge, indexer of the world\'s ideas. Knows where to find anything — even things better left unfound.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 35 },
    compulsorySkills: ['Accounting', 'Library Use', 'Own Language'],
    specialtyChoices: [
      { pick: 1, from: ['Other Language (Latin)', 'Other Language (French)', 'Other Language (German)', 'Other Language (Greek)'], label: 'Other language' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'military_officer',
    name: 'Military Officer',
    description: 'Leads soldiers, plans operations, and makes hard decisions under fire. Discipline is everything.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 20, max: 70 },
    compulsorySkills: ['Accounting', 'Firearms', 'First Aid', 'Navigate', 'Persuade', 'Psychology'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'nurse',
    name: 'Nurse',
    description: 'Provides care where doctors leave off. Patient, precise, and used to seeing people at their worst.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 35 },
    compulsorySkills: ['First Aid', 'Medicine', 'Psychology', 'Science (Biology)'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'occultist',
    name: 'Occultist',
    description: 'Scholar of the hidden and forbidden. Reads between the lines of history and finds things that chill the blood.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 65 },
    compulsorySkills: ['Anthropology', 'History', 'Library Use', 'Natural World', 'Occult'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'pilot',
    name: 'Pilot',
    description: 'Takes to the skies with skill and daring. Aircraft give access to places no road can reach.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Electrical Repair', 'Mechanical Repair', 'Navigate', 'Pilot (Aircraft)', 'Science (Astronomy)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'police_detective',
    name: 'Police Detective',
    description: 'Works cases from inside the law. Access to records, morgues, and informants others can\'t reach.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 20, max: 50 },
    compulsorySkills: ['Disguise', 'Fighting (Brawl)', 'Firearms', 'Law', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'professor',
    name: 'Professor',
    description: 'Academic and educator. Knows a great deal about something — and a little about everything else.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 70 },
    compulsorySkills: ['Library Use', 'Own Language', 'Psychology'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
      { pick: 1, from: ['Anthropology', 'Archaeology', 'History', 'Occult', 'Science (any)'], label: 'Academic specialty (1)' },
      { pick: 1, from: ['Anthropology', 'Archaeology', 'History', 'Occult', 'Natural World'], label: 'Academic specialty (2)' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'sailor',
    name: 'Sailor',
    description: 'Knows the sea in all its moods. Whether naval or merchant, a sailor has seen what lies beyond the horizon.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 9, max: 35 },
    compulsorySkills: ['Fighting (Brawl)', 'First Aid', 'Mechanical Repair', 'Natural World', 'Navigate', 'Pilot (Boat)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'scientist',
    name: 'Scientist',
    description: 'Pursues empirical truth through experiment and observation. Some truths, however, resist any rational framework.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 35 },
    compulsorySkills: ['Electrical Repair', 'Library Use', 'Other Language (any)', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Science (Biology)', 'Science (Chemistry)', 'Science (Physics)', 'Science (Astronomy)', 'Science (Mathematics)'], label: 'Science specialty (1)' },
      { pick: 1, from: ['Science (Biology)', 'Science (Chemistry)', 'Science (Physics)', 'Science (Astronomy)', 'Science (Mathematics)'], label: 'Science specialty (2)' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'soldier',
    name: 'Soldier',
    description: 'Trained to fight, survive, and follow orders. War leaves marks no one talks about in polite company.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Climb', 'First Aid', 'Stealth', 'Survival'],
    specialtyChoices: [
      { pick: 1, from: ['Fighting (Brawl)', 'Fighting (Bayonet)'], label: 'Melee skill' },
      { pick: 1, from: ['Firearms (Rifle/Shotgun)', 'Firearms (Handgun)', 'Firearms (Machine Gun)'], label: 'Primary Firearms' },
      { pick: 1, from: ['Firearms (Rifle/Shotgun)', 'Firearms (Handgun)', 'Firearms (Machine Gun)'], label: 'Secondary Firearms' },
    ],
    cashAndAssets: cr => cash(cr),
  },
];

export default OCCUPATIONS;
