// CoC 7e Occupation Data — Investigator Handbook (full list)
// Source: occupations_full.csv
// cashAndAssets uses Credit Rating midpoint for display

const mid = (min, max) => Math.floor((min + max) / 2);

const cash = (cr) => ({
  cash:          cr * 2,
  assets:        cr * 50,
  spendingLimit: Math.max(1, Math.floor(cr / 5) * 5),
});

const OCCUPATIONS = [
  {
    id: 'accountant',
    name: 'Accountant',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Either employed within a business or working as a freelance consultant. Diligence and attention to detail makes most accountants good researchers able to support investigations through careful analysis of financial records.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 70 },
    compulsorySkills: ['Accounting', 'Law', 'Library Use', 'Listen', 'Persuade', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'acrobat',
    name: 'Acrobat',
    erasAvailable: [],
    description: 'May be amateur-athletes competing in staged meets or professionals employed with circuses, carnivals, or theatrical performances.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 9, max: 20 },
    compulsorySkills: ['Climb', 'Dodge', 'Jump', 'Throw', 'Spot Hidden', 'Swim', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'actor_stage',
    name: 'Stage Actor',
    erasAvailable: [],
    description: 'Usually a stage actor with a background in the classics. Considers themselves legitimate and looks down upon the commercial film industry.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 9, max: 40 },
    compulsorySkills: ['Art/Craft (Acting)', 'Disguise', 'Fighting', 'History', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'actor_film',
    name: 'Film Star',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Movie star living a flashy high-profile life, ever in the media spotlight. By the late twentieth century film actors command greater respect and higher fees than ever before.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 20, max: 90 },
    compulsorySkills: ['Art/Craft (Acting)', 'Disguise', 'Drive Auto', 'Psychology', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'agency_detective',
    name: 'Agency Detective',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Company operative for a well-known detective agency such as Pinkerton or Burns. Plainclothes detective sent out to solve mysteries, prevent murders, and locate missing people.',
    skillPointsFormula: 'EDU × 2 + (STR × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.STR * 2, s.DEX * 2),
    creditRating: { min: 20, max: 45 },
    compulsorySkills: ['Fighting (Brawl)', 'Firearms', 'Law', 'Library Use', 'Psychology', 'Stealth', 'Track'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'alienist',
    name: 'Alienist',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'In the 1920s the term given for those who treat mental illness — early psychiatrists. Psychoanalysis is barely known in the U.S. and intellectual wars rage between alienists, psychiatrists, and neurologists.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 60 },
    compulsorySkills: ['Law', 'Listen', 'Medicine', 'Other Language', 'Psychoanalysis', 'Psychology', 'Science (Biology)', 'Science (Chemistry)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'animal_trainer',
    name: 'Animal Trainer',
    erasAvailable: [],
    description: 'May be employed by film studios, a traveling circus, or a horse stable. Whether training guide dogs or teaching a lion to jump through a flaming hoop, the trainer usually works alone in close proximity with their animals.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or POW × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.POW * 2),
    creditRating: { min: 10, max: 40 },
    compulsorySkills: ['Animal Handling', 'Jump', 'Listen', 'Natural World', 'Science (Zoology)', 'Stealth', 'Track', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'antiquarian',
    name: 'Antiquarian',
    erasAvailable: [],
    description: 'A person who delights in the timeless excellence of design and ancient lore. Probably the most Lovecraft-like occupation available. An independent income allows exploration of things old and obscure.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 70 },
    compulsorySkills: ['Appraise', 'Art/Craft (any)', 'History', 'Library Use', 'Other Language', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'antique_dealer',
    name: 'Antique Dealer',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Usually owns their own shop, retails items out of their home, or goes on extended buying trips making a profit on reselling to urban stores.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 50 },
    compulsorySkills: ['Accounting', 'Appraise', 'Drive Auto', 'History', 'Library Use', 'Navigate'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'archaeologist',
    name: 'Archaeologist',
    erasAvailable: [],
    description: 'The study and exploration of the past. In the 1920s successful archaeologists were celebrities seen as explorers and adventurers. Some used scientific methods; others were happy to apply brute force.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 40 },
    compulsorySkills: ['Appraise', 'Archaeology', 'History', 'Other Language (any)', 'Library Use', 'Spot Hidden', 'Mechanical Repair', 'Navigate or Science (any)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'architect',
    name: 'Architect',
    erasAvailable: [],
    description: 'Trained to design and plan buildings from small home conversions to multi-million dollar projects. Must be aware of local planning laws, health and safety regulations, and general public safety.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 70 },
    compulsorySkills: ['Accounting', 'Art/Craft (Technical Drawing)', 'Law', 'Own Language', 'Library Use or Computer Use', 'Persuade', 'Psychology', 'Science (Mathematics)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'artist',
    name: 'Artist',
    erasAvailable: [],
    description: 'May be a painter, sculptor, etc. Sometimes self-absorbed and driven with a particular vision. The artist\'s ego must be hardy to surmount initial obstacles and critical appraisal.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or POW × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.POW * 2),
    creditRating: { min: 9, max: 50 },
    compulsorySkills: ['Art/Craft (any)', 'History or Natural World', 'Other Language', 'Psychology', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'asylum_attendant',
    name: 'Asylum Attendant',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Chosen more for strength and size than medical learning. Works in state and county facilities for the mentally ill.',
    skillPointsFormula: 'EDU × 2 + (STR × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.STR * 2, s.DEX * 2),
    creditRating: { min: 8, max: 20 },
    compulsorySkills: ['Dodge', 'Fighting (Brawl)', 'First Aid', 'Listen', 'Psychology', 'Stealth'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_assassin',
    name: 'Assassin (Criminal)',
    erasAvailable: [],
    description: 'Cold-blooded killers of the underworld. Usually hired from out of town. They arrive, do their work, and quickly disappear. Strictly business.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Disguise', 'Electrical Repair', 'Fighting', 'Firearms', 'Locksmith', 'Mechanical Repair', 'Stealth', 'Psychology'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'athlete',
    name: 'Athlete',
    erasAvailable: [],
    description: 'Probably plays in a professional baseball, football, cricket, or basketball team. Successful athletes enjoy celebrity within their arena of expertise.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 70 },
    compulsorySkills: ['Climb', 'Jump', 'Fighting (Brawl)', 'Ride', 'Swim', 'Throw', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'author',
    name: 'Author',
    erasAvailable: [],
    description: 'Uses words to define and explore the human condition. Solitary work with variable rewards. Typically spends months or years researching then withdrawing for periods of intense creation.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Literature)', 'History', 'Library Use', 'Natural World or Occult', 'Other Language', 'Own Language', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'aviator',
    name: 'Aviator',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'A stunt pilot working at carnivals or offering daring leisure rides. Fame could be won at organized air races. Many learned to fly during the Great War and still hold military commissions.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Accounting', 'Electrical Repair', 'Listen', 'Mechanical Repair', 'Navigate', 'Pilot (Aircraft)', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_bank_robber',
    name: 'Bank Robber (Criminal)',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west'],
    description: 'Gang-based criminals specializing in robbing banks. Breaking and entering, threats, and physical coercion are all standard tools.',
    skillPointsFormula: 'EDU × 2 + (STR × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.STR * 2, s.DEX * 2),
    creditRating: { min: 5, max: 75 },
    compulsorySkills: ['Drive Auto', 'Electrical or Mechanical Repair', 'Fighting', 'Firearms', 'Intimidate', 'Locksmith', 'Operate Heavy Machinery', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'bartender',
    name: 'Bartender',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Everyone\'s friend. For some it\'s a career, for many it\'s a means to an end. In the 1920s the profession is made illegal by Prohibition — but speakeasies still need bartenders.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 8, max: 25 },
    compulsorySkills: ['Accounting', 'Fighting (Brawl)', 'Listen', 'Psychology', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'big_game_hunter',
    name: 'Big Game Hunter',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Skilled trackers who earn a living leading safaris for wealthy clients. Most are specialized in one part of the world such as the Canadian woods or African plains.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 20, max: 50 },
    compulsorySkills: ['Firearms', 'Natural World', 'Navigate', 'Science (Biology or Botany or Zoology)', 'Stealth', 'Track', 'Listen or Spot Hidden', 'Other Language or Survival (any)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'book_dealer',
    name: 'Book Dealer',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'May own a retail outlet or niche mail order service. Many have wealthy or regular clients who provide lists of sought-after and rare works.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 40 },
    compulsorySkills: ['Accounting', 'Appraise', 'Drive Auto', 'History', 'Library Use', 'Own Language', 'Other Language'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_bootlegger',
    name: 'Bootlegger/Thug (Criminal)',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Soldiers of organized crime. Supported by criminal organizations and expected to take the fall for the gangsters above them. Their silence and loyalty is expected and rewarded.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 5, max: 30 },
    compulsorySkills: ['Drive Auto', 'Fighting', 'Firearms', 'Psychology', 'Stealth', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'bounty_hunter',
    name: 'Bounty Hunter',
    erasAvailable: [],
    description: 'Tracks down and returns fugitives to justice. May freely cross state lines in pursuit of their quarry and may show little regard for civil rights. Breaking and entering, threats, and physical abuse are all part of the bag of tricks.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Drive Auto', 'Electronic or Electrical Repair', 'Law', 'Psychology', 'Track', 'Stealth', 'Fighting or Firearms'],
    specialtyChoices: [
      { pick: 1, from: ['Fast Talk', 'Charm', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'boxer_wrestler',
    name: 'Boxer/Wrestler',
    erasAvailable: [],
    description: 'Professional fighters managed by promoters and usually locked into contracts. Some make a living from illegal bare-knuckle fights arranged by organized crime.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 9, max: 60 },
    compulsorySkills: ['Dodge', 'Fighting (Brawl)', 'Intimidate', 'Jump', 'Psychology', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_burglar',
    name: 'Burglar (Criminal)',
    erasAvailable: [],
    description: 'Cat burglars and second-story men. Highly specialized in breaking and entering. Research and planning focused criminal enterprises.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 5, max: 40 },
    compulsorySkills: ['Appraise', 'Climb', 'Electrical or Mechanical Repair', 'Listen', 'Locksmith', 'Sleight of Hand', 'Stealth', 'Spot Hidden'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'butler_valet_maid',
    name: 'Butler/Valet/Maid',
    erasAvailable: [],
    description: 'Employed in a servant capacity. The butler ranks as the highest male servant in a large household, in charge of the dining room, wine cellar and pantry. A valet or lady\'s maid provides personal services.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 40 },
    compulsorySkills: ['Accounting or Appraise', 'Art/Craft (any e.g. Cook, Tailor, Barber)', 'First Aid', 'Listen', 'Psychology', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'chauffeur',
    name: 'Chauffeur',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Either directly employed by an individual or works for an agency that hires both car and chauffeur. Drives for successful business people and political representatives.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 10, max: 40 },
    compulsorySkills: ['Drive Auto', 'Listen', 'Mechanical Repair', 'Navigate', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'clergy',
    name: 'Member of the Clergy',
    erasAvailable: [],
    description: 'Assigned to parishes or sent on evangelical missions. Bears witness to confessions. Different churches have different priorities and hierarchies.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 60 },
    compulsorySkills: ['Accounting', 'History', 'Library Use', 'Listen', 'Other Language', 'Psychology', 'any one other skill'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'computer_programmer',
    name: 'Computer Programmer/Technician',
    erasAvailable: ['modern'],
    description: 'Designing, writing, testing, debugging, and maintaining source code. May work freelance or within a software development house.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 70 },
    compulsorySkills: ['Computer Use', 'Electrical Repair', 'Electronics', 'Library Use', 'Science (Mathematics)', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'hacker',
    name: 'Hacker',
    erasAvailable: ['modern'],
    description: 'Uses computers as a means of protest or for criminal gain. Illegally breaks into computers and other user accounts. Sometimes referred to as hacktivists.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 70 },
    compulsorySkills: ['Computer Use', 'Electrical Repair', 'Electronics', 'Library Use', 'Spot Hidden', 'any two other skills'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_conman',
    name: 'Conman (Criminal)',
    erasAvailable: [],
    description: 'Smooth talkers who fleece wealthy individuals or communities. Some schemes are elaborate involving teams of scam men; others are simple affairs requiring only one con man and a few minutes.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 10, max: 65 },
    compulsorySkills: ['Appraise', 'Art/Craft (Acting)', 'Law or Other Language', 'Listen', 'Psychology', 'Sleight of Hand'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'cowboy',
    name: 'Cowboy/Girl',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west'],
    description: 'Works the ranges and ranches of the West. Some own their own ranches but many are hired where and when work is available. Good money can be made on the rodeo circuit.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 20 },
    compulsorySkills: ['Dodge', 'First Aid or Natural World', 'Jump', 'Ride', 'Survival (any)', 'Throw', 'Track', 'Fighting or Firearms'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'craftsperson',
    name: 'Craftsperson',
    erasAvailable: [],
    description: 'Skilled in the manual production of items. Trades include furniture, jewelry, watchmaking, pottery, blacksmithing, textiles, carpentry, glassblowing, and more.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 10, max: 40 },
    compulsorySkills: ['Accounting', 'Art/Craft (any two)', 'Mechanical Repair', 'Natural World', 'Spot Hidden', 'any two other skills as personal specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal',
    name: 'Criminal',
    erasAvailable: [],
    description: 'Freelance criminal. Opportunistic jacks of all trades — pickpockets, thugs, and general miscreants. Works solo or occasionally teams up with others when the reward is worth the effort.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or APP × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.APP * 2),
    creditRating: { min: 5, max: 65 },
    compulsorySkills: ['Art/Craft (Acting) or Disguise', 'Appraise', 'Fighting or Firearms', 'Locksmith or Mechanical Repair', 'Stealth', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'cult_leader',
    name: 'Cult Leader',
    erasAvailable: [],
    description: 'Either a firm believer in the dogma they impart to cult members or simply in it for money and power. America has always generated new religions from the New England Transcendentalists to modern movements.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Accounting', 'Occult', 'Psychology', 'Spot Hidden', 'any two other skills as specialties'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'deprogrammer',
    name: 'Deprogrammer',
    erasAvailable: ['modern'],
    description: 'Persuades or forces people to abandon allegiance to cults. Normally hired by relatives of an individual who has joined a cult. Less extreme deprogrammers work with those who have voluntarily left as exit counselors.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 50 },
    compulsorySkills: ['Drive Auto', 'Fighting (Brawl) or Firearms', 'History', 'Occult', 'Psychology', 'Stealth'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'designer',
    name: 'Designer',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Works in many fields from fashion to furniture. May work freelance or for a design house designing consumer products, processes, laws, games, or graphics.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 60 },
    compulsorySkills: ['Accounting', 'Art/Craft (Photography)', 'Art/Craft (any)', 'Computer Use or Library Use', 'Mechanical Repair', 'Psychology', 'Spot Hidden', 'any one other skill as personal specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'dilettante',
    name: 'Dilettante',
    erasAvailable: [],
    description: 'Self-supporting, living off an inheritance, trust fund, or other income that requires no work. Money frees the dilettante to be eccentric and outspoken. In the 1920s some might be flappers or sheiks.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 50, max: 99 },
    compulsorySkills: ['Art/Craft (any)', 'Firearms', 'Other Language', 'Ride', 'any three other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'diver',
    name: 'Diver',
    erasAvailable: [],
    description: 'Could work in military, law enforcement, or civilian occupations like sponge gathering, salvage, conservation, or treasure hunting.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Diving', 'First Aid', 'Mechanical Repair', 'Pilot (Boat)', 'Science (Biology)', 'Spot Hidden', 'Swim', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'doctor',
    name: 'Doctor of Medicine',
    erasAvailable: [],
    description: 'Most likely a general practitioner, surgeon, or specialist. Three common aims: helping patients, gaining money and prestige, and promoting a more rational society. In the 1920s many older physicians obtained licenses before strict medical school requirements existed.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 80 },
    compulsorySkills: ['First Aid', 'Medicine', 'Other Language (Latin)', 'Psychology', 'Science (Biology)', 'Science (Pharmacy)', 'any two other skills as academic or personal specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'drifter',
    name: 'Drifter',
    erasAvailable: [],
    description: 'Wandering life chosen to compensate for a social, philosophical, or economic lack. The drifter takes jobs sometimes for days or months but is disposed to solve problems with mobility and isolation.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2, s.STR * 2),
    creditRating: { min: 0, max: 5 },
    compulsorySkills: ['Climb', 'Jump', 'Listen', 'Navigate', 'Stealth', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'driver',
    name: 'Driver',
    erasAvailable: [],
    description: 'Professional driver. May work for a company, private individual, or possibly have their own cab or rig.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 20 },
    compulsorySkills: ['Accounting', 'Drive Auto', 'Listen', 'Mechanical Repair', 'Navigate', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'editor',
    name: 'Editor',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Assigns stories to reporters, writes editorials, deals with crises, and meets deadlines. Large newspapers have many editors; small newspapers may have only one who is also the owner.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 30 },
    compulsorySkills: ['Accounting', 'History', 'Own Language', 'Psychology', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'elected_official',
    name: 'Elected Official',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Popularly-elected officials from small-town mayors to federal senators. The mayors of big cities rule like little kingdoms. Federal positions carry the most clout.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 50, max: 90 },
    compulsorySkills: ['Charm', 'History', 'Intimidate', 'Fast Talk', 'Listen', 'Own Language', 'Persuade', 'Psychology'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'engineer',
    name: 'Engineer',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Applies scientific knowledge, mathematics, and ingenuity to design solutions for technical problems. Employed in civilian business or the military. Includes inventors.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Art/Craft (Technical Drawing)', 'Electrical Repair', 'Library Use', 'Mechanical Repair', 'Operate Heavy Machine', 'Science (Engineering)', 'Science (Physics)', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'entertainer',
    name: 'Entertainer',
    erasAvailable: [],
    description: 'Clown, singer, dancer, comedian, juggler, musician, or anyone who earns a living in front of an audience. Loves to be seen and loves the applause.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 9, max: 70 },
    compulsorySkills: ['Art/Craft (e.g. Acting, Singer, Comedian etc.)', 'Disguise', 'Listen', 'Psychology', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'explorer',
    name: 'Explorer',
    erasAvailable: [],
    description: 'In the early twentieth century there are still unknown areas of the world. Scientific grants, private donations, and museum contracts combined with publishing rights generate enough money to support this exciting lifestyle.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2, s.STR * 2),
    creditRating: { min: 55, max: 80 },
    compulsorySkills: ['Climb or Swim', 'Firearms', 'History', 'Jump', 'Natural World', 'Navigate', 'Other Language', 'Survival'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'farmer',
    name: 'Farmer',
    erasAvailable: [],
    description: 'Agricultural worker who might own the land or be employed to raise crops and livestock. The 1920s are the first decade where the urban population of the U.S. outnumbers the rural population.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Farming)', 'Drive Auto (or Wagon)', 'Mechanical Repair', 'Natural World', 'Operate Heavy Machinery', 'Track', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'federal_agent',
    name: 'Federal Agent',
    erasAvailable: ['modern'],
    description: 'Vast variety of federal law enforcement. Some uniformed like U.S. Marshals, others plainclothes like the FBI. Operates similar to detectives.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 40 },
    compulsorySkills: ['Drive Auto', 'Fighting (Brawl)', 'Firearms', 'Law', 'Persuade', 'Stealth', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_fence',
    name: 'Fence (Criminal)',
    erasAvailable: [],
    description: 'Trades in stolen property. Principally a middleman between thieves and buyers, taking a cut of the profit or buying stolen goods at a very low price.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 20, max: 40 },
    compulsorySkills: ['Accounting', 'Appraise', 'Art/Craft (Forgery)', 'History', 'Library Use', 'Spot Hidden', 'any one other skill'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'firefighter',
    name: 'Firefighter',
    erasAvailable: [],
    description: 'Civil servants employed by the communities they serve. Work around the clock on shifts lasting several days eating and sleeping within the fire station. Organized along military lines.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Climb', 'Dodge', 'Drive Auto', 'First Aid', 'Jump', 'Mechanical Repair', 'Operate Heavy Machinery', 'Throw'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'foreign_correspondent',
    name: 'Foreign Correspondent',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Elite of news reporters. Work on salary, enjoy expense accounts, and travel the globe. Natural disasters, political upheaval, and war are the primary focus.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 40 },
    compulsorySkills: ['History', 'Other Language', 'Own Language', 'Listen', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'forensic_surgeon',
    name: 'Forensic Surgeon',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Highly specialized. Employed by a city, county, or state to conduct autopsies, determine causes of death, and make recommendations to the prosecutor\'s office. Often called to give testimony at criminal proceedings.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 40, max: 60 },
    compulsorySkills: ['Other Language (Latin)', 'Library Use', 'Medicine', 'Persuade', 'Science (Biology)', 'Science (Forensics)', 'Science (Pharmacy)', 'Spot Hidden'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_forger',
    name: 'Forger/Counterfeiter (Criminal)',
    erasAvailable: [],
    description: 'Artists of the criminal world specializing in forging official documents, deeds, and signatures. Beginners make fake IDs; the best engrave plates for counterfeiting currency.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 60 },
    compulsorySkills: ['Accounting', 'Appraise', 'Art/Craft (Forgery)', 'History', 'Library Use', 'Spot Hidden', 'Sleight of Hand', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'gambler',
    name: 'Gambler',
    erasAvailable: [],
    description: 'The dandies of the criminal world. Sharp dressers who base their life upon chance. Whether frequenting the racetrack, card table, or casino, some are backed by outside investors.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 8, max: 50 },
    compulsorySkills: ['Accounting', 'Art/Craft (Acting)', 'Listen', 'Psychology', 'Sleight of Hand', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'gangster_boss',
    name: 'Gangster Boss',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Oversees the business, makes deals, and determines how to solve problems. For the most part untouchable, able to field a small army of underlings. Unlikely to get their hands dirty.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 60, max: 95 },
    compulsorySkills: ['Fighting', 'Firearms', 'Law', 'Listen', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'gangster_underling',
    name: 'Gangster Underling',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Has specific areas of responsibility such as overseeing illicit shipments and collecting protection money.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 20 },
    compulsorySkills: ['Drive Auto', 'Fighting', 'Firearms', 'Psychology', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_gun_moll',
    name: 'Gun Moll (Criminal)',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Female professional criminal. While many are fiercely independent, some are at the beck and call of mobster boyfriends — though in reality the moll may be the one running the show.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 10, max: 80 },
    compulsorySkills: ['Art/Craft (any)', 'Drive Auto', 'Listen', 'Stealth', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
      { pick: 1, from: ['Fighting (Brawl)', 'Firearms (Handgun)'], label: 'Combat skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'gentleman_lady',
    name: 'Gentleman/Lady',
    erasAvailable: [],
    description: 'A man or woman of good breeding and courteous behavior. Usually independently wealthy by inheritance or regular allowance. In the 1920s would certainly have had at least one servant.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 40, max: 90 },
    compulsorySkills: ['Art/Craft (any)', 'Firearms (Rifle/Shotgun)', 'History', 'Other Language (any)', 'Navigate', 'Ride'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'hobo',
    name: 'Hobo',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west'],
    description: 'Workers who wander. Riding the rails continually, penniless poets and vagabonds. Life on the road or rails is dangerous. The hobo faces hostility from police, close-knit communities, and railroad staff.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 0, max: 5 },
    compulsorySkills: ['Art/Craft (any)', 'Climb', 'Jump', 'Listen', 'Locksmith or Sleight of Hand', 'Navigate', 'Stealth', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'hospital_orderly',
    name: 'Hospital Orderly',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'In charge of emptying waste, cleaning rooms, taxiing patients, and any other odd job requiring slightly more skill than a janitor. Has access to drugs and medical records.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 6, max: 15 },
    compulsorySkills: ['Electrical Repair', 'Fighting (Brawl)', 'First Aid', 'Listen', 'Mechanical Repair', 'Psychology', 'Stealth'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'investigative_journalist',
    name: 'Investigative Journalist',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Reports and keeps independent of the corruption they witness. Work is similar to that of a private detective. The best investigative journalists sometimes resort to subterfuge to gain information.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Art or Photography)', 'History', 'Library Use', 'Own Language', 'Psychology', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'reporter',
    name: 'Reporter',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Works in news and media. Assigned to specific beats like police, sports, or business. Carries a press pass but the real work is similar to that of a private detective.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Acting)', 'History', 'Listen', 'Own Language', 'Psychology', 'Stealth', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'judge',
    name: 'Judge',
    erasAvailable: [],
    description: 'An official who presides over court legal proceedings either alone or within a group of peers. Either appointed or elected, sometimes for life. Most judges are licensed attorneys.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 50, max: 80 },
    compulsorySkills: ['History', 'Intimidate', 'Law', 'Library Use', 'Listen', 'Own Language', 'Persuade', 'Psychology'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'laboratory_assistant',
    name: 'Laboratory Assistant',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Performs laboratory and administrative tasks under supervision of a lead scientist. Tasks include sampling, testing, recording results, and ensuring health and safety policies are followed.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 30 },
    compulsorySkills: ['Electrical Repair', 'Other Language', 'Science (Chemistry)', 'Science (any two others)', 'Spot Hidden', 'any one other skill as personal specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Computer Use', 'Library Use'], label: 'Research tool' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'laborer',
    name: 'Laborer',
    erasAvailable: [],
    description: 'Factory workers, mill hands, stevedores, road crews. Often expert in the use of power tools, lifting gear, and other equipment despite being technically unskilled.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Drive Auto', 'Electrical Repair', 'Fighting', 'First Aid', 'Mechanical Repair', 'Operate Heavy Machinery', 'Throw', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'lawyer',
    name: 'Lawyer',
    erasAvailable: [],
    description: 'Learned in the law. Acts as attorney, counsel, or solicitor. May be hired or appointed by a court or privately retained by a wealthy client. With the right client, a lawyer could become a celebrity.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 80 },
    compulsorySkills: ['Accounting', 'Law', 'Library Use', 'Psychology', 'any two other skills'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'librarian',
    name: 'Librarian',
    erasAvailable: [],
    description: 'Employed by public institutions or universities. Responsible for cataloging and maintaining stock and dealing with lender enquiries. In modern times also a keeper of electronic media and databases.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 35 },
    compulsorySkills: ['Accounting', 'Library Use', 'Other Language', 'Own Language', 'any four other skills as personal specialties or specialist reading topics'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'lumberjack',
    name: 'Lumberjack',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west'],
    description: 'Works in forestry. Expert with chainsaws and heavy equipment in the wilderness.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Climb', 'Dodge', 'Fighting (Chainsaw)', 'First Aid', 'Jump', 'Mechanical Repair', 'Natural World or Science (Biology or Botany)', 'Throw'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'mechanic',
    name: 'Mechanic/Skilled Tradesperson',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Carpenters, stonemasons, plumbers, electricians, millwrights, mechanics. All trades requiring specialized training. Usually have their own unions — almost guilds — that bargain with employers.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 40 },
    compulsorySkills: ['Art/Craft (Carpentry, Welding, Plumbing etc.)', 'Climb', 'Drive Auto', 'Electrical Repair', 'Mechanical Repair', 'Operate Heavy Machinery', 'any two other skills as personal era or trade specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'military_officer',
    name: 'Military Officer',
    erasAvailable: [],
    description: 'Command rank. Most commissions demand higher education. Officers are respected for life — even a long-retired officer has the right to call himself Captain or General.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 20, max: 70 },
    compulsorySkills: ['Accounting', 'Firearms', 'Navigate', 'First Aid', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'miner',
    name: 'Miner',
    erasAvailable: [],
    description: 'Works underground extracting ore. Connected to union officials and political organizations. Life underground is dangerous and demanding.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Climb', 'Geology', 'Jump', 'Mechanical Repair', 'Operate Heavy Machinery', 'Stealth', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'missionary',
    name: 'Missionary',
    erasAvailable: [],
    description: 'Visits remote corners of the globe dispensing the word of God. May be Catholic, Protestant, Islamic, or from another branch of faith. Christian, Islamic, Buddhist, and Hindu teachers can be encountered worldwide in all eras.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 0, max: 30 },
    compulsorySkills: ['Art/Craft (any)', 'First Aid', 'Mechanical Repair', 'Medicine', 'Natural World', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'mountain_climber',
    name: 'Mountain Climber',
    erasAvailable: [],
    description: 'Most are weekend sportsmen. A few have the reputations needed to attract financing for major climbs. By the 1920s all major American and Alpine peaks have been conquered; Himalayan expeditions are underway.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 30, max: 60 },
    compulsorySkills: ['Climb', 'First Aid', 'Jump', 'Listen', 'Navigate', 'Other Language', 'Survival (Alpine or as appropriate)', 'Track'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'museum_curator',
    name: 'Museum Curator',
    erasAvailable: [],
    description: 'Responsible for a large university facility or smaller specialized museum. Often specializing in local geology or other such topics.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 30 },
    compulsorySkills: ['Accounting', 'Appraise', 'Archaeology', 'History', 'Library Use', 'Occult', 'Other Language', 'Spot Hidden'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'musician',
    name: 'Musician',
    erasAvailable: [],
    description: 'May perform in an orchestra, group, or solo. Getting noticed is hard and getting a recording contract is difficult. The 1920s is the Jazz Age and musicians work in small combos and dance orchestras.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Instrument)', 'Listen', 'Psychology', 'any four other skills'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'nurse',
    name: 'Nurse',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Trained healthcare assistant usually working in hospitals, nursing homes, or with general practitioners. Assists individuals with activities contributing to health or recovery.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['First Aid', 'Listen', 'Medicine', 'Psychology', 'Science (Biology)', 'Science (Chemistry)', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'occultist',
    name: 'Occultist',
    erasAvailable: [],
    description: 'Student of esoteric secrets and arcane magic. Fully believes in paranormal abilities and actively attempts to discover these powers. Most are familiar with a broad range of magical theories.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 65 },
    compulsorySkills: ['Anthropology', 'History', 'Library Use', 'Occult', 'Other Language', 'Science (Astronomy)', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'outdoorsman',
    name: 'Outdoorsman/Outdoorswoman',
    erasAvailable: [],
    description: 'Spends much of their time living in the wilderness, often alone for long periods. Commonly skilled in hunting and fishing and able to be self-sufficient in all but the harshest environments.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 5, max: 20 },
    compulsorySkills: ['Firearms', 'First Aid', 'Listen', 'Natural World', 'Navigate', 'Spot Hidden', 'Survival (any)', 'Track'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'parapsychologist',
    name: 'Parapsychologist',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Attempts to observe, record, and study paranormal instances. Sometimes nicknamed ghost hunters. Much of their time is spent debunking fake mediums rather than recording actual evidence.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Anthropology', 'Art/Craft (Photography)', 'History', 'Library Use', 'Occult', 'Other Language', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'pharmacist',
    name: 'Pharmacist',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Licensed by individual states. May be employed in a hospital or drug store, or own a dispensary. Has access to all manner of chemicals and drugs.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 35, max: 75 },
    compulsorySkills: ['Accounting', 'First Aid', 'Other Language (Latin)', 'Library Use', 'Science (Pharmacy)', 'Science (Chemistry)'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'photographer',
    name: 'Photographer',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Works freelance, for an advertising firm, or in a portrait studio. The elite are drawn from the worlds of art, journalism, and wildlife conservation.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Photography)', 'Psychology', 'Science (Chemistry)', 'Stealth', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'photojournalist',
    name: 'Photojournalist',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Essentially reporters who use cameras but also expected to write prose to accompany images. In the 1920s newsreels came into being with heavy bulky 35mm film equipment hauled around the globe.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 30 },
    compulsorySkills: ['Art/Craft (Photography)', 'Climb', 'Other Language', 'Psychology', 'Science (Chemistry)', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'pilot',
    name: 'Pilot',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Professional aviators employed by business or the military. In the U.S. there was no national regulation of pilots until the Air Commerce Act of 1926.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 20, max: 70 },
    compulsorySkills: ['Electrical Repair', 'Mechanical Repair', 'Navigate', 'Operate Heavy Machine', 'Pilot (Aircraft)', 'Science (Astronomy)', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'police_detective',
    name: 'Police Detective',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Plainclothes detective. Examines crime scenes, gathers evidence, conducts interviews, and tries to solve homicides, major burglaries, and other felonies.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 20, max: 50 },
    compulsorySkills: ['Art/Craft (Acting) or Disguise', 'Firearms', 'Law', 'Listen', 'Psychology', 'Spot Hidden', 'any one other skill'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'uniformed_police',
    name: 'Uniformed Police Officer',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Employed by cities and towns, county sheriffs\' departments, and state or regional police forces. Job may be on foot, in a patrol car, or at a desk.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Fighting (Brawl)', 'Firearms', 'First Aid', 'Law', 'Psychology', 'Spot Hidden', 'Drive Automobile or Ride'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'private_investigator',
    name: 'Private Investigator',
    erasAvailable: [],
    description: 'Acts in non-police situations gathering evidence for private clients. Tracks fleeing spouses or business partners. Works for the guilty and innocent alike as long as the fee is paid.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Art/Craft (Photography)', 'Disguise', 'Law', 'Library Use', 'Psychology', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'professor',
    name: 'Professor',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Academics employed by colleges and universities. Qualified to teach and perform competent research. The occupation indicates a Ph.D. capable of earning tenure at universities around the world.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 70 },
    compulsorySkills: ['Library Use', 'Other Language', 'Own Language', 'Psychology', 'any four other skills as academic era or personal specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'prospector',
    name: 'Prospector',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west'],
    description: 'Roams the mountains endlessly searching for the big strike. Though the Gold Rush days are long gone the independent prospector is still a feature of the American West. In these days oil may be as good as gold.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 0, max: 10 },
    compulsorySkills: ['Climb', 'First Aid', 'History', 'Mechanical Repair', 'Navigate', 'Science (Geology)', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'prostitute',
    name: 'Prostitute',
    erasAvailable: [],
    description: 'May be a high-rolling call girl, male gigolo, or streetwalker. Often driven by circumstance. A few work independently; most are kept in the business by ruthless pimps.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 5, max: 50 },
    compulsorySkills: ['Art/Craft (any)', 'Dodge', 'Psychology', 'Sleight of Hand', 'Stealth', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'psychiatrist',
    name: 'Psychiatrist',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Physician specialized in the diagnosis and treatment of mental disorders. Authorized to prescribe psychiatric medication. At the turn of the twentieth century psychoanalytic theories were still relatively new.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 30, max: 80 },
    compulsorySkills: ['Other Language', 'Listen', 'Medicine', 'Persuade', 'Psychoanalysis', 'Psychology', 'Science (Biology)', 'Science (Chemistry)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'psychologist',
    name: 'Psychologist/Psychoanalyst',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight'],
    description: 'Clinical psychologists work with patients using a range of therapeutic tools. In the 1920s the study of human behavior was a rather new field primarily focused on Freudian analysis.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 10, max: 40 },
    compulsorySkills: ['Accounting', 'Library Use', 'Listen', 'Persuade', 'Psychoanalysis', 'Psychology', 'any two other skills as academic era or personal specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'researcher',
    name: 'Researcher',
    erasAvailable: [],
    description: 'Academic world or private sector. Oil companies hire geologists, anthropologists study primitive tribes, archaeologists spend years unearthing treasures. Some go on to become field researchers.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['History', 'Library Use', 'Other Language', 'Spot Hidden', 'any three fields of study'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'sailor_naval',
    name: 'Sailor (Naval)',
    erasAvailable: [],
    description: 'Naval sailors go through basic training. Assigned rates and stations upon graduation. In the U.S. Navy standard enlistment is four years active duty followed by two years inactive reserve.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Electrical or Mechanical Repair', 'Fighting', 'Firearms', 'First Aid', 'Navigate', 'Pilot (Boat)', 'Survival (Sea)', 'Swim'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'sailor_commercial',
    name: 'Sailor (Commercial)',
    erasAvailable: [],
    description: 'Works aboard fishing vessels, charter boats, or haulage tankers. During Prohibition many charter boat captains found lucrative trade ferrying thirsty customers to the 3-mile limit.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 20, max: 40 },
    compulsorySkills: ['First Aid', 'Mechanical Repair', 'Natural World', 'Navigate', 'Pilot (Boat)', 'Spot Hidden', 'Swim'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'salesperson',
    name: 'Salesperson',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Promotes and sells employer\'s goods or services. Most spend time traveling and entertaining clients. The 1920s is the decade of the entrepreneur and the traveling salesperson is part of everyday life.',
    skillPointsFormula: 'EDU × 2 + APP × 2',
    skillPointsCalc: s => s.EDU * 2 + s.APP * 2,
    creditRating: { min: 9, max: 40 },
    compulsorySkills: ['Accounting', 'Drive Auto', 'Listen', 'Psychology', 'Stealth or Sleight of Hand', 'any one other skill'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'scientist',
    name: 'Scientist',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Natural philosophers who delve reality in pursuit of knowledge. Although specializing in one field, any scientist worth their salt is well-versed in several branches of science.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 50 },
    compulsorySkills: ['Any three science specialisms', 'Other Language', 'Own Language', 'Spot Hidden', 'Computer Use or Library Use'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'secretary',
    name: 'Secretary',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Ranges from highly-paid executive assistants to those in the typing pool. Being at the hub of the business, most secretaries know more about the inner workings than their bosses do.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or APP × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.APP * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Accounting', 'Art/Craft (Typing or Short Hand)', 'Own Language', 'Library Use or Computer Use', 'Psychology', 'any one other skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'shopkeeper',
    name: 'Shopkeeper',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Owner of a small shop, market stall, or restaurant. Usually self-employed, possibly family-run. The 1920s saw many women opening their own hairdressing and millinery shops.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 20, max: 40 },
    compulsorySkills: ['Accounting', 'Electrical Repair', 'Listen', 'Mechanical Repair', 'Psychology', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_smuggler',
    name: 'Smuggler (Criminal)',
    erasAvailable: [],
    description: 'Always a lucrative and high-risk business. The smuggler usually has a public profession as cover allowing them to transport illicit products to a needy market.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 20, max: 60 },
    compulsorySkills: ['Firearms', 'Listen', 'Navigate', 'Drive Auto or Pilot (Aircraft or Boat)', 'Psychology', 'Sleight of Hand', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'soldier',
    name: 'Soldier/Marine',
    erasAvailable: [],
    description: 'Enlisted ranks of the Army and Marines from Private up through Gunnery Sergeant. All go through basic training — boot camp — where raw recruits are taught how to march, shoot, and salute.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Climb or Swim', 'Dodge', 'Fighting', 'Firearms', 'Stealth', 'Survival', 'First Aid or Mechanical Repair or Other Language', 'First Aid or Mechanical Repair or Other Language'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'spy',
    name: 'Spy',
    erasAvailable: [],
    description: 'Works for the intelligence community of a political state or organization. May appear in any form of occupation as cover. Some work deep cover for many years; others change identity at the drop of a hat.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 20, max: 60 },
    compulsorySkills: ['Art/Craft (Acting) or Disguise', 'Firearms', 'Listen', 'Other Language', 'Psychology', 'Sleight of Hand', 'Stealth'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_street_punk',
    name: 'Street Punk (Criminal)',
    erasAvailable: [],
    description: 'Typically young street hoods looking to hook up with real gangsters. Experience is limited to stealing cars, shoplifting, mugging, and burglary.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 3, max: 10 },
    compulsorySkills: ['Climb', 'Fighting', 'Firearms', 'Jump', 'Sleight of Hand', 'Stealth', 'Throw'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'student',
    name: 'Student/Intern',
    erasAvailable: [],
    description: 'May be enrolled at a college or university or receiving on-the-job training as an intern with minimal compensation. Students tend to be younger characters.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 5, max: 10 },
    compulsorySkills: ['Language (Own or Other)', 'Library Use', 'Listen', 'any three fields of study', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'stuntman',
    name: 'Stuntman',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Film and television industry. Simulates falls from buildings, car crashes, and other catastrophes. In the 1920s there are no equivalent organizations nor any regulation — accidents and fatalities are frequent.',
    skillPointsFormula: 'EDU × 2 + (DEX × 2 or STR × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.DEX * 2, s.STR * 2),
    creditRating: { min: 10, max: 50 },
    compulsorySkills: ['Climb', 'Dodge', 'Electrical Repair or Mechanical Repair', 'Fighting', 'First Aid', 'Jump', 'Swim', 'Diving or Drive Automobile or Pilot (any) or Ride'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'taxi_driver',
    name: 'Taxi Driver',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Works for large or small cab companies or possibly has their own cab and license. Required to obtain a special license including a background check by the police detective bureau.',
    skillPointsFormula: 'EDU × 2 + DEX × 2',
    skillPointsCalc: s => s.EDU * 2 + s.DEX * 2,
    creditRating: { min: 9, max: 30 },
    compulsorySkills: ['Accounting', 'Drive Auto', 'Electrical Repair', 'Fast Talk', 'Mechanical Repair', 'Navigate', 'Spot Hidden', 'any one other skill as personal or era specialty'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'criminal_thug',
    name: 'Thug (Criminal)',
    erasAvailable: [],
    description: 'Soldiers of organized crime who do the dirty work. Expected to take the fall for the gangsters above them. Their silence and loyalty is expected and rewarded.',
    skillPointsFormula: 'EDU × 2 + STR × 2',
    skillPointsCalc: s => s.EDU * 2 + s.STR * 2,
    creditRating: { min: 5, max: 30 },
    compulsorySkills: ['Drive Auto', 'Fighting', 'Firearms', 'Psychology', 'Stealth', 'Spot Hidden'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'tribe_member',
    name: 'Tribe Member',
    erasAvailable: [],
    description: 'In a tribe the primacy of kinship and custom is self-evident. In place of a blanket of law, the tribal personality defers to personal honor. Exile has real power in such a setting.',
    skillPointsFormula: 'EDU × 2 + (STR × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.STR * 2, s.DEX * 2),
    creditRating: { min: 0, max: 15 },
    compulsorySkills: ['Climb', 'Listen', 'Natural World', 'Occult', 'Spot Hidden', 'Swim', 'Survival (any)', 'Fighting or Throw'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'undertaker',
    name: 'Undertaker',
    erasAvailable: [],
    description: 'Manages funeral rites including burial or cremation of the dead. Performs embalming, dressing, casketing, and cosmetizing the deceased. Licensed by the state.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 40 },
    compulsorySkills: ['Accounting', 'Drive Auto', 'History', 'Occult', 'Psychology', 'Science (Biology)', 'Science (Chemistry)'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'union_activist',
    name: 'Union Activist',
    erasAvailable: ['modern', 'classic_1920s'],
    description: 'Organizers and leaders of unions. Caught between big business wishing to destroy them, politicians alternately befriending them, communists trying to infiltrate their ranks, and criminal mobs trying to take them over.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 5, max: 30 },
    compulsorySkills: ['Accounting', 'Fighting (Brawl)', 'Law', 'Listen', 'Operate Heavy Machinery', 'Psychology'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'valet',
    name: 'Valet',
    erasAvailable: [],
    description: 'Provides personal services to an employer — maintaining their clothes, running baths, making travel arrangements, managing their employer\'s diary, and organizing household finances.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 40 },
    compulsorySkills: ['Accounting or Appraise', 'Art/Craft (any e.g. Cook, Tailor, Barber)', 'First Aid', 'Listen', 'Psychology', 'Spot Hidden', 'any two other skills as personal or era specialties'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'waiter_waitress',
    name: 'Waitress/Waiter',
    erasAvailable: [],
    description: 'Serves customers in a hotel, bar, or eating establishment. Traditionally low-paid, earns tips by providing good service. A technically illegal profession during Prohibition — but speakeasies still need waitstaff.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or DEX × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.DEX * 2),
    creditRating: { min: 9, max: 20 },
    compulsorySkills: ['Accounting', 'Art/Craft (any)', 'Dodge', 'Listen', 'Psychology', 'any one skill as personal or era specialty'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'clerk_executive',
    name: 'Clerk/Executive',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Habitually underpaid with those recognised as having talent earmarked for promotion. The work is drudgery for most, with the pay barely enough to survive.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 20 },
    compulsorySkills: ['Accounting', 'Language (Own or Other)', 'Law', 'Library Use or Computer Use', 'Listen', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 1, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skill' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'manager',
    name: 'Middle/Senior Manager',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'old_west', 'regency'],
    description: 'Middle or senior manager in a small to large corporation. Higher salaries with greater responsibilities and say in how the business is managed day-to-day.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 20, max: 80 },
    compulsorySkills: ['Accounting', 'Other Language', 'Law', 'Psychology', 'any two other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'zealot',
    name: 'Zealot',
    erasAvailable: [],
    description: 'Intense and vision-driven, scorning an easy life. Agitates for a better life for humanity or some group imagined most worthwhile. Some fanatics promote beliefs through violence; the peaceable majority may be just as implacable.',
    skillPointsFormula: 'EDU × 2 + (APP × 2 or POW × 2)',
    skillPointsCalc: s => s.EDU * 2 + Math.max(s.APP * 2, s.POW * 2),
    creditRating: { min: 0, max: 30 },
    compulsorySkills: ['History', 'Psychology', 'Stealth', 'any three other skills as personal or era specialties'],
    specialtyChoices: [
      { pick: 2, from: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'], label: 'Interpersonal skills' },
    ],
    cashAndAssets: cr => cash(cr),
  },
  {
    id: 'zookeeper',
    name: 'Zookeeper',
    erasAvailable: ['modern', 'classic_1920s', 'gaslight', 'regency'],
    description: 'Responsible for feeding and care of animals in their charge. Often specialized in a particular breed. Can use the Medicine skill on animals.',
    skillPointsFormula: 'EDU × 4',
    skillPointsCalc: s => s.EDU * 4,
    creditRating: { min: 9, max: 40 },
    compulsorySkills: ['Animal Handling', 'Accounting', 'Dodge', 'First Aid', 'Natural World', 'Medicine', 'Science (Pharmacy)', 'Science (Zoology)'],
    specialtyChoices: [],
    cashAndAssets: cr => cash(cr),
  },
];

export default OCCUPATIONS;
